# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5c13a875270a3f2e1d183e5ae6d9697a959f1266755cdab9278671d9ab100a17f80ab0811d9614ea68461e28a2e697a3314672d930191d0855a7acb64b67159
  twilio:
    account_sid: 0123456789abcdef
    auth_token: 0123456789abcdef
    phone_number: '+12345678901'
  email:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'gmail.com'
    user_name: 'yourname@gmail.com'
    password: 'yourpassword'
    authentication: 'plain'
    enable_starttls_auto: true
  google_maps_api_key: 0123456789abcdef0123456789abcdef0123456

test:
  secret_key_base: e5c13a875270a3f2e1d183e5ae6d9697a959f1266755cdab9278671d9ab100a17f80ab0811d9614ea68461e28a2e697a3314672d930191d0855a7acb64b67159
  twilio:
    account_sid: 0123456789abcdef
    auth_token: 0123456789abcdef
    phone_number: '+12345678901'
  email:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'gmail.com'
    user_name: 'yourname@gmail.com'
    password: 'yourpassword'
    authentication: 'plain'
    enable_starttls_auto: true
  google_maps_api_key: 0123456789abcdef0123456789abcdef0123456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: e5c13a875270a3f2e1d183e5ae6d9697a959f1266755cdab9278671d9ab100a17f80ab0811d9614ea68461e28a2e697a3314672d930191d0855a7acb64b67159
  twilio:
    account_sid: 0123456789abcdef
    auth_token: 0123456789abcdef
    phone_number: '+12345678901'
  email:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'gmail.com'
    user_name: 'yourname@gmail.com'
    password: 'yourpassword'
    authentication: 'plain'
    enable_starttls_auto: true
  google_maps_api_key: 0123456789abcdef0123456789abcdef0123456
